### ISSUE TITLE
[Feature] Model 추가

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DietLog#12]
## Description

- Model 추가

## Tasks

- [x] 내 정보 화면 MyInfo Model
- [x] 식단 Meal Model
- [x] 운동 Exercise Model
- [x] 운동 카테고리 Exercise Category Model
