### ISSUE TITLE
[Design] Search view 추가

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DietLog#23]
## Description

- Search view 추가

## Tasks

- [x] 최근 검색어 레이블
- [x] 최근 검색어 콜렉션뷰
- [x] 최근 검색어 없을 때 레이블
- [x] 최근 검색어 전체 삭제 버튼
- [x] 서치바
- [x] 검색 결과 화면
- [x] 검색 결과 없을 때 레이블
