### ISSUE TITLE
[Feature] MyInfo 화면 구성

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DietLog#30]
## Description

- MyInfo 화면을 구성합니다

## Tasks

- [x] 닉네임 표시
- [x] 날짜에 맞는 정보 불러오기 - 오늘 / 탭한 날짜
- [x] 오늘 날짜에 입력된 정보 저장하기
- [x] 수정 버튼 눌렀을 때 정보 수정하기
- [x] 3개 모두 공란일 때 저장 누르면, 알림창 표시 - 삭제 혹은 입력해 주세요
