### ISSUE TITLE
[Feature] Exercise Category 화면 구성

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DietLog#42]
## Description

- Exercise Category 화면 구성

## Tasks

- [x] Exercise Category 추가
- [x] Exercise Category 보여주기
- [x] 타이틀 수정
- [x] Exercise Category 삭제
