### ISSUE TITLE
[Feature] Exercise edit 화면 구성

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DietLog#46]
## Description

- Exercise edit 화면 구성

## Tasks

- [x] 카테고리 없을 때 레이블 표시
- [x] 카테고리 있을 때 카테고리 표시
- [x] 카테고리 추가하기 버튼 화면 연결
- [x] 카테고리 선택 시 변수에 저장
- [x] 입력받은 주소로 api 받아오기
- [x] 주소 및 카테고리 선택 시 저장하고 알림창 표시 후 전화면으로 되돌아가기

**Comment by jooYeonIya** [comment]
콜백 지옥 개선 및 api error에 대한 처리가 없기 때문에 추후 추가 필요
