### ISSUE TITLE
[Feature] Search 화면 최근 검색어 부분 구성

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DietLog#54]
## Description

- Search 화면 최근 검색어 부분 구성

## Tasks

- [x] 최근 검색어 저장하기
- [x] 최근 검색어 불러오기
- [x] 최근 검색어 없을 때 레이블 표시
- [x] 최근 검색어 전체 삭제 
- [x] 최근 검색어 한 개 삭제
