### ISSUE TITLE
[Design] Meal View Cell 디자인 개선

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DietLog#66]
## Description

- Meal View Cell 디자인 개선

## Tasks

- [x] Meal View Cell 선택시 회색 미표시
- [x] 구분선 미표시
- [x] cell 간격 띄우기
- [x] 테이블뷰 스크롤 미표시
