### ISSUE TITLE
[Refactor] Meal 화면

### ISSUE THREAD

**Issue by jooYeonIya** [jooYeonIya/DietLog#89]
## Task

- [x] 주석 정리
- [x] 변수 정리
- [x] 함수 정리
- [x] 인덴트 정리
- [x] 수정 매커니즘 재정의
- [x] 갤러리 사용 여부 확인하기
- [x] 사진 크기에 맞춰서 imageView 늘어나게 하기

**Comment by jooYeonIya** [comment]
수정 매커니즘 재정의
: 기존 데이터의 식단을 확인할 때 바로 사용자가 수정할 수 있었고 수정 버튼을 누르면 바로 Update 되었다
: 수정 후에는 기존 데이터의 식단을 확인할 때 바로 사용자가 수정할 수 없고 수정 버튼을 누른 후에 사용자와 상호작용이 가능하게 변경했다
